# Generated by Django 4.1.7 on 2023-03-30 18:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/files'), upload_to='')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='')),
                ('format', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
