# Generated by Django 4.1.7 on 2023-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='slug',
            field=models.SlugField(default='dummy-slug', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='model',
            name='file',
            field=models.FileField(upload_to='model/files'),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(upload_to='model/images'),
        ),
    ]
